### ISSUE TITLE
Example not running

### ISSUE THREAD

**Issue by SebastianSchuetze** [tmeckel/pulumi-azuredevops-samples#1]
Hi @tmeckel, I tried your example together with the install instruction of the pulumi AzD provider to build it locally. The first part worked perfectly, but I can't run the example. I also tried my own pulumi project. In both cases I get the following error:

```
pulumi:pulumi:Stack (azdo-sample-nodejs-dev):
    error: Running program '/mnt/f/repos/general_github/pulumi-azuredevops-samples/project-management/nodejs' failed with an unhandled exception:
    Error: Cannot find module './Agent/index'
    Require stack:
    - /home/razorspoint/.pulumi/node_modules/@pulumi/azuredevops/index.js
    - /mnt/f/repos/general_github/pulumi-azuredevops-samples/project-management/nodejs/index.ts
    - /mnt/f/repos/general_github/pulumi-azuredevops-samples/project-management/nodejs/node_modules/@pulumi/pulumi/cmd/run/run.js
    - /mnt/f/repos/general_github/pulumi-azuredevops-samples/project-management/nodejs/node_modules/@pulumi/pulumi/cmd/run/index.js
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
        at Function.Module._load (internal/modules/cjs/loader.js:842:27)
        at Module.require (internal/modules/cjs/loader.js:1026:19)
        at require (internal/modules/cjs/helpers.js:72:18)
        at Object.<anonymous> (/home/razorspoint/.pulumi/node_modules/@pulumi/index.ts:8:1)
        at Module._compile (internal/modules/cjs/loader.js:1138:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
        at Module.load (internal/modules/cjs/loader.js:986:32)
        at Function.Module._load (internal/modules/cjs/loader.js:879:14)
        at Module.require (internal/modules/cjs/loader.js:1026:19)
```

I am using Ubuntu LTS 18.04. Do you know what this agent module is?

**Comment by SebastianSchuetze** [comment]
And I ran also the `yarn link "@pulumi/azuredevops"` command of course and in the node_modules folder under @pulumi I can see the folder as well as TypeScript in VSCode is not complaining about missing modules.
But with `pulumi up` it is not working

**Comment by SebastianSchuetze** [comment]
Checked a bit more. I don't know what the problem was, but I rebuild the project with make again, but I am facing another problem now. If I run now `pulumi up` I get the following

```
Previewing update (dev):
     Type                             Name                    Plan       Info
 +   pulumi:pulumi:Stack              azdo-sample-nodejs-dev  create     
     └─ pulumi:providers:azuredevops  default_0_1_7                      1 error
 
Diagnostics:
  pulumi:providers:azuredevops (default_0_1_7):
    error: no resource plugin 'azuredevops-v0.1.7' found in the workspace or on your $PATH, install the plugin using `pulumi plugin install resource azuredevops v0.1.7`
```

And I guess pulumi is talking about your provider. Any points what I generally might do wrong?

**Comment by tmeckel** [comment]
Hi @SebastianSchuetze please ensure that `$HOME/go/bin` and `$HOME/.pulumi/bin` are in your `PATH` environment variable. I recommended adding the two paths to your `.bashrc` and `.profile` (`.bash_profile`), so that the paths are available each time you start a shell.

**Comment by SebastianSchuetze** [comment]
Thanks for the feedback. I now hacked around a bit. I have to say it is one of the very few times I used Ubuntu.

I would like to make a PR to the local build doc and suggest some additions to make it easier for others to install it with a clean environment. Main problems which I got:

1 often during make build / install I had the message to not have enough permission to mkdir / rm. With my limited knowledge I only ran the make build / install with sudo
   * to make this work I had to start sh with sudo and copy $PATH variable `sudo -E sudo env "PATH=$PATH" sh` and then I could run it
2. In your build process you copy the nodejs module to .pulumi/node_modules and then use `yarn link` to link it somehow it didn't work during `make install` and I had to navigate manually to the module folder and link it myself
3. some of the command are incomplete or too manual I think. But I make a PR to suggest the changes and then you can tell me if that is good or why it shouldn't be like it.
4. pulumi PATH entry is added and stays, but go PATH entry not. I guess during install of pulumi it is adding itself permanently to it.

I used Ubuntu 18.04 on WSL2 (insider build) also with VSCode remote development. I also think that this combination confused me to whether WSL or terminals in VSCode are started with the right permission to run the script.

Is it ok if I create a docker file to have the build environment properly setup? So it would be the same for everybody.

**Comment by tmeckel** [comment]
> 1 often during make build / install I had the message to not have enough permission to mkdir / rm. With my limited knowledge I only ran the make build / install with sudo
> 
> * to make this work I had to start sh with sudo and copy $PATH variable `sudo -E sudo env "PATH=$PATH" sh` and then I could run it
> 

This a behavior of WSL1 that I personally (and some other people as well) observed a couple of times now. The main issue here seems to be the fact that the commands are executed via a shell instance that is started via the `make` process and not by a (login) interactive shell. My suspicion is that the bug is inside the emulation layer that Microsoft created for WSL1. WSL2, unlike WSL1, is a real (lightweight) virtual machine with a real Linux kernel.

By the way, the `v2` branch now contains a special fix in `commons.mk` for WSL1.

> 1. In your build process you copy the nodejs module to .pulumi/node_modules and then use `yarn link` to link it somehow it didn't work during `make install` and I had to navigate manually to the module folder and link it myself
> 2. some of the command are incomplete or too manual I think. But I make a PR to suggest the changes and then you can tell me if that is good or why it shouldn't be like it.
> 3. pulumi PATH entry is added and stays, but go PATH entry not. I guess during install of pulumi it is adding itself permanently to it.
> 

The complete build environment is copied from the [boilerplate repository from Pulumi]( https://github.com/pulumi/pulumi-tf-provider-boilerplate) with some adjustments and because the overall plan is to make the provider an official Pulumi provider, I had to adopt Pulumi's build infrastructure.

The onboarding process for the provider has already been started with Pulumi, but I cannot say when it will be finished. If the provider has been promoted to an official Pulumi provider the cumbersome process to build and install the provider itself will become obsolete though.

> I used Ubuntu 18.04 on WSL2 (insider build) also with VSCode remote development. I also think that this combination confused me to whether WSL or terminals in VSCode are started with the right permission to run the script.
> 

I'd prefer WSL2 for development purposes because of the pesky issues is faced with WSL1, but as WSL2 requires Hyper-V support enabled on Windows 10, it collides with VirtualBox that I utilize to run real virtual machines. As long as Oracle won't provide a fix that will support running VirtualBox on a system with Hyper-V enabled (like VMWare did), I'm stuck with WSL1.

> Is it ok if I create a docker file to have the build environment properly setup? So it would be the same for everybody.

Sure, all contributions are welcomed.

**Comment by tmeckel** [comment]
@SebastianSchuetze Because you successfully got all examples running, I suppose that I can close the issue. Feel free to reopen it.
